---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  type: NodePort
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongo-port
    nodePort: 32017
    protocol: TCP
  selector:
    app: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
      name: mongodb
    spec:
      containers:
      - name: mongodb
        image: ekambaram/mongodb:3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          protocol: TCP
          name: mongo-port
        env:
        - name: MONGODB_USER
          value: "docker"
        - name: MONGODB_PASS
          value: "docker"
        - name: MONGODB_DATABASE
          value: "companydb"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactivecs
  name: reactivecs
spec:
  type: NodePort
  ports:
  - name: reactivecs
    port: 8080
    targetPort: rcs-port
    nodePort: 30080
    protocol: TCP
  selector:
    app: reactivecs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reactivecs
spec:
  template:
    metadata:
      labels:
        app: reactivecs
      name: reactivecs
    spec:
      containers:
      - name: reactivecs
        image: ekambaram/reactive-company-search:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          name: rcs-port
